# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TokenNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('strength_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('momentum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('detected_at', models.DateTimeField()),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_links', to='narratives.narrative')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_links', to='tokens.token')),
            ],
            options={
                'ordering': ['-detected_at'],
                'constraints': [models.UniqueConstraint(fields=('token', 'narrative'), name='unique_token_narrative')],
            },
        ),
    ]
