# Generated by Django 5.2.17 on 2026-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
