# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(blank=True, choices=[('discovered', 'Discovered'), ('watching', 'Watching'), ('developing', 'Developing'), ('confirmed', 'Confirmed'), ('breakout', 'Breakout'), ('invalidated', 'Invalidated')], max_length=12)),
                ('to_state', models.CharField(choices=[('discovered', 'Discovered'), ('watching', 'Watching'), ('developing', 'Developing'), ('confirmed', 'Confirmed'), ('breakout', 'Breakout'), ('invalidated', 'Invalidated')], max_length=12)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reasons', models.JSONField(blank=True, default=list, help_text='List of why-now reason strings')),
                ('triggered_at', models.DateTimeField(db_index=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='tokens.token')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('discovered', 'Discovered'), ('watching', 'Watching'), ('developing', 'Developing'), ('confirmed', 'Confirmed'), ('breakout', 'Breakout'), ('invalidated', 'Invalidated')], db_index=True, max_length=12)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('probability_2x', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('probability_3x', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('narrative_summary', models.CharField(blank=True, max_length=255)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('is_priority', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(db_index=True, default=False)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='predictions.prediction')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tokens.token')),
                ('alert_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['token', '-triggered_at'], name='alerts_aler_token_i_4b8296_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['token', '-created_at'], name='alerts_aler_token_i_d6debc_idx'),
        ),
    ]
