# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('safety_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('liquidity_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('momentum_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('holder_growth_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wallet_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buy_pressure_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_structure_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('narrative_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creator_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('opportunity_score', models.DecimalField(db_index=True, decimal_places=2, max_digits=6)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weights_version', models.CharField(default='v1', max_length=32)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tokens.token')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token', '-timestamp'], name='scoring_tok_token_i_57d36e_idx')],
            },
        ),
    ]
