# Generated by Django 5.2.17 on 2026-08-31 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('score', models.DecimalField(decimal_places=2, help_text='0-100, higher is safer', max_digits=6)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('EXTREME', 'Extreme')], db_index=True, max_length=10)),
                ('hard_rejection', models.BooleanField(db_index=True, default=False)),
                ('hard_rejection_reasons', models.JSONField(blank=True, default=list)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='tokens.token')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token', '-timestamp'], name='scoring_tok_token_i_6254b6_idx')],
            },
        ),
    ]
