# Generated by Django 5.2.17 on 2026-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_tokensafetycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenscore',
            name='score_2x',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deterministic 0-100 score, NOT a calibrated probability -- see Prediction.probability_2x (Batch 12) for that.', max_digits=6),
        ),
        migrations.AddField(
            model_name='tokenscore',
            name='score_3x',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deterministic 0-100 score, NOT a calibrated probability -- see Prediction.probability_3x (Batch 12) for that.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='buy_pressure_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='creator_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='holder_growth_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='liquidity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='momentum_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='narrative_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='price_structure_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='safety_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tokenscore',
            name='wallet_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
