# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('predictions', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_timestamp', models.DateTimeField(db_index=True)),
                ('initial_price', models.DecimalField(decimal_places=18, max_digits=36)),
                ('initial_market_cap', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('max_multiple', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reached_1_5x', models.BooleanField(default=False)),
                ('reached_2x', models.BooleanField(default=False)),
                ('reached_3x', models.BooleanField(default=False)),
                ('reached_5x', models.BooleanField(default=False)),
                ('reached_10x', models.BooleanField(default=False)),
                ('time_to_2x', models.DurationField(blank=True, null=True)),
                ('time_to_3x', models.DurationField(blank=True, null=True)),
                ('time_to_5x', models.DurationField(blank=True, null=True)),
                ('tracking_complete', models.BooleanField(db_index=True, default=False)),
                ('last_outcome_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='alerts.alert')),
                ('prediction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome', to='predictions.prediction')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='tokens.token')),
            ],
            options={
                'ordering': ['-reference_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TokenOutcomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_label', models.CharField(choices=[('5m', '5 minutes'), ('10m', '10 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('1h', '1 hour'), ('3h', '3 hours'), ('6h', '6 hours'), ('12h', '12 hours'), ('24h', '24 hours')], max_length=4)),
                ('recorded_at', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('liquidity_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('volume_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('holder_count', models.PositiveIntegerField(blank=True, null=True)),
                ('max_gain_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='outcomes.tokenoutcome')),
            ],
            options={
                'ordering': ['outcome', 'recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tokenoutcome',
            index=models.Index(fields=['tracking_complete', 'reference_timestamp'], name='outcomes_to_trackin_05cff0_idx'),
        ),
        migrations.AddConstraint(
            model_name='tokenoutcomesnapshot',
            constraint=models.UniqueConstraint(fields=('outcome', 'offset_label'), name='unique_outcome_offset'),
        ),
    ]
