# Generated by Django 5.2.17 on 2026-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_config', models.JSONField()),
                ('new_config', models.JSONField()),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True)),
                ('expected_improvement', models.JSONField(blank=True, default=dict)),
                ('actual_improvement', models.JSONField(blank=True, default=dict)),
                ('change_source', models.CharField(choices=[('ai_automatic', 'AI Automatic'), ('ai_recommended_approved', 'AI Recommended, User Approved'), ('manual', 'Manual')], max_length=32)),
                ('model_version', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_liquidity_usd', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('min_volume_5m_usd', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('min_holder_count', models.PositiveIntegerField(default=0)),
                ('max_risk_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('min_opportunity_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('min_probability_2x', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('min_probability_3x', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('alert_cooldown_minutes', models.PositiveIntegerField(default=20)),
                ('max_alerts_per_hour', models.PositiveIntegerField(default=5)),
                ('narrative_settings', models.JSONField(blank=True, default=dict)),
                ('smart_money_settings', models.JSONField(blank=True, default=dict)),
                ('autonomy_mode', models.CharField(choices=[('ai_automatic', 'AI Automatic'), ('ai_recommended', 'AI Recommended'), ('manual', 'Manual')], default='ai_automatic', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
