# Generated by Django 5.2.17 on 2026-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mock', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='mock', max_length=32)),
                ('address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('decimals', models.PositiveSmallIntegerField(default=9)),
                ('creator_address', models.CharField(blank=True, db_index=True, max_length=64)),
                ('launched_at', models.DateTimeField(blank=True, help_text='On-chain mint creation time', null=True)),
                ('mint_authority_revoked', models.BooleanField(blank=True, null=True)),
                ('freeze_authority_revoked', models.BooleanField(blank=True, null=True)),
                ('is_mutable_metadata', models.BooleanField(blank=True, null=True)),
                ('top_holder_pct_at_launch', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Still being actively monitored/ingested')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='tokens_toke_is_acti_37372e_idx')],
            },
        ),
    ]
