# Generated by Django 5.2.17 on 2026-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='token',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"twitter": "...", "discord": "..."}'),
        ),
        migrations.AddField(
            model_name='token',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
