# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mock', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='mock', max_length=32)),
                ('address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('classification', models.CharField(choices=[('smart_money', 'Smart Money'), ('insider', 'Insider'), ('creator', 'Creator'), ('sniper', 'Sniper'), ('bot', 'Bot'), ('bundled', 'Bundled Wallet'), ('market_maker', 'Market Maker'), ('normal', 'Normal Trader'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_multiple', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('median_multiple', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_multiple', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('avg_holding_time', models.DurationField(blank=True, null=True)),
                ('trade_count', models.PositiveIntegerField(default=0)),
                ('successful_2x_count', models.PositiveIntegerField(default=0)),
                ('successful_3x_count', models.PositiveIntegerField(default=0)),
                ('successful_5x_count', models.PositiveIntegerField(default=0)),
                ('preferred_token_age', models.CharField(blank=True, choices=[('0_5m', '0-5 minutes'), ('5_30m', '5-30 minutes'), ('30m_3h', '30 minutes - 3 hours'), ('3h_plus', '3+ hours')], max_length=10)),
                ('preferred_market_cap_range', models.CharField(blank=True, max_length=32)),
                ('reputation_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 smart-money wallet score', max_digits=6, null=True)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mock', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='mock', max_length=32)),
                ('tx_signature', models.CharField(db_index=True, max_length=128, unique=True)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('amount_tokens', models.DecimalField(decimal_places=9, max_digits=36)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='tokens.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['wallet', '-occurred_at'], name='wallets_wal_wallet__18f234_idx'), models.Index(fields=['token', '-occurred_at'], name='wallets_wal_token_i_eab3c7_idx')],
            },
        ),
    ]
