# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mock', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='mock', max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('holder_count', models.PositiveIntegerField()),
                ('top_holder_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('top5_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('top10_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creator_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('insider_pct', models.DecimalField(blank=True, decimal_places=2, help_text='From wallet clustering, if known', max_digits=6, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_snapshots', to='tokens.token')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token', '-timestamp'], name='holders_hol_token_i_d8e9d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('token', 'timestamp', 'source'), name='unique_holder_snapshot')],
            },
        ),
    ]
