# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mock', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='mock', max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=18, max_digits=36)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('volume_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('volume_5m', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('volume_15m', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('volume_1h', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('buy_volume_5m', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('sell_volume_5m', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unique_buyers_5m', models.PositiveIntegerField(blank=True, null=True)),
                ('unique_sellers_5m', models.PositiveIntegerField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tokens.token')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token', '-timestamp'], name='market_data_token_i_8db773_idx')],
                'constraints': [models.UniqueConstraint(fields=('token', 'timestamp', 'source'), name='unique_token_snapshot')],
            },
        ),
    ]
