# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquiditySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mock', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='mock', max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pool_address', models.CharField(blank=True, max_length=64)),
                ('liquidity_usd', models.DecimalField(decimal_places=6, max_digits=24)),
                ('liquidity_sol', models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True)),
                ('lp_locked', models.BooleanField(blank=True, null=True)),
                ('lp_burned', models.BooleanField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_snapshots', to='tokens.token')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token', '-timestamp'], name='liquidity_l_token_i_d34a0e_idx')],
                'constraints': [models.UniqueConstraint(fields=('token', 'timestamp', 'source'), name='unique_liquidity_snapshot')],
            },
        ),
    ]
