# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_watch', models.BooleanField(default=False, help_text='Dashboard-only by default per PRD S36')),
                ('notify_developing', models.BooleanField(default=False)),
                ('notify_confirmed', models.BooleanField(default=True)),
                ('notify_breakout', models.BooleanField(default=True)),
                ('notify_invalidated', models.BooleanField(default=True)),
                ('notify_priority', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
