# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('feature_set_version', models.CharField(blank=True, max_length=32)),
                ('split_boundaries', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='e.g. "2x_probability_classifier"', max_length=64)),
                ('version', models.CharField(help_text='e.g. "v0.7"', max_length=32)),
                ('trained_at', models.DateTimeField()),
                ('feature_set', models.JSONField(blank=True, default=list)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, max_length=512)),
                ('is_deployed', models.BooleanField(db_index=True, default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('training_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_versions', to='ml.trainingdataset')),
            ],
            options={
                'ordering': ['-trained_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_model_name_version')],
            },
        ),
    ]
